on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Delete huge unnecessary tools folder at:https://github.com/orgs/community/discussions/25678#discussioncomment-3248696
        run: rm -rf /opt/hostedtoolcache;rm -rf /usr/share/dotnet/;df -h;sudo apt-get remove -y '^ghc-8.*';sudo apt-get remove -y '^dotnet-.*';sudo apt-get remove -y '^llvm-.*';sudo apt-get remove -y 'php.*';sudo  apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel;sudo apt-get autoremove -y;sudo apt-get clean;sudo apt list --installed;sudo dpkg-query -W -f='${Installed-Size;8}  ${Package}\n' | sort -n;df -h
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: zhengguang/vllm:latest
